---
# tasks file for roles/web
- name: 安装httpd
  dnf:
    name: httpd 
    state: present
- name: 渲染
  template:
    src: index.html.j2 
    dest: /var/www/html/index.html
  notify: restart httpd
- name: 开机自启
  service:
    name: httpd 
    state: started
    enabled: true

- name: 修改 httpd 监听端口为 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    line: 'Listen 8080'
  notify: restart httpd
